# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title fastSum3
#' @description sums of a vector
#' @details Sums of a vector
#' @author Rick Qiu
#' @export fastSum3
#' @aliases fastSum3
#' @param x Numeric Vector
#' @return a double number
#' @useDynLib BasicCpp
#' @examples
#' fastSum3(1:100)
NULL

fastSum3 <- function(x) {
    .Call('BasicCpp_fastSum3', PACKAGE = 'BasicCpp', x)
}

